### PR TITLE
Adding a file for Travis CI

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ksterker** [comment]
Any specific reason you provided this build script? Just curious ...

**Comment by ghost** [comment]
I searched free/libre RPG games (I like this type of game and would like to do one in C99), and I found yours. I try to contribute a bit to free/libre projects that I use or at least try.

**Comment by ghost** [comment]
However, I am curious why there is no issue tab. I searched it, because the repo seems out-of-sync, last commit in 2014 but last news and version in 2016 ! http://adonthell.nongnu.org/news/

**Comment by ksterker** [comment]
On Tue, Nov 8, 2016 at 7:56 PM, Nicola Spanti notifications@github.com
wrote:

> However, I am curious why there is no issue tab. I searched it, because
> the repo seems out-of-sync, last commit in 2014 but last news and version
> in 2016 ! http://adonthell.nongnu.org/news/

It's complicated :-). The short version is, Github has the "next
generation"/in development version. The old version has been kept on
Savannah, in an ancient CVS repo. Now that work on the project has been
stopped, I did a little bit of a rehash of the old code, so that it will
continue to work. As such, it is still kept on Savannah, but also moved to
Git. See http://savannah.nongnu.org/forum/forum.php?forum_id=8628 for a
brief list of what is where.

It's probably less than ideal, but at the time the split happened, nobody
would anticipate that development would end in this state, sadly ...

Kai

**Comment by ghost** [comment]
Ok, thanks for the explanation.

**Pull request merged**
